### ISSUE TITLE
Definition of alpha conversion underspecified

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#1]
_migrated from Trac, where originally posted by **kohlhase** on 26-Oct-2007 4:33am_

Florian Rabe reports:

"This object binding (B , v , C ) can be replaced in Ω by binding (B , z , C') where z is a variable not occurring free in C and C' is obtained from C by replacing each free (i.e., not bound by any intermediate binding construct) occurrence of v by z."

1) It is left out what happens if there are variables with attributions.

It is reasonable to allow even mutually recursive attributions:

  binding(let, attribution(v_1,value -> t_1), attribution(v_2,value -> t_2), C)
i.e.,
  let v_1 := t_1 and v_2 := t_2 in C

where t_1 and t_2 may contain v_1 and v_2.

Therefore, alpha conversion must rename variables not only in the scope, but also in all bound variables themselves.

2) The case of duplicate variables is unclear, too. What happens if a variable occurs twice, but with different attributions? And what happens to
  binding(b, x, attribution(y, k -> x), x, C)?

I think duplicate bound variable should be forbidden. They are intended to be pointless anyway.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 30-May-2014 4:00pm_

I believe it is accepted that an OMBIND causes the variables to be bound within the OMBVAR and in the body(s) after it, but _not_ in the head. The latter point has useful applications.

This definitely needs to be made explicit in the standard.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/30
