### ISSUE TITLE
Reconsider attribution examples

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#103]
_migrated from Trac, where originally posted by **clange** on 24-Nov-2008 5:21pm_

In a discussion about an ASCII syntax for OpenMath objects (and notation definitions), we are currently talking about use cases for attributions.  In [jomdoc:comment:ticket:48:18 my latest comment on that discussion], I wonder whether the example of attributing a OpenMath object with a visual rendering is still up to date, given that MathML with parallel markup is an alternative for that.  If this example is obsolete, you may have to come up with a different one for the OM3 spec.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **david** on 25-Nov-2008 12:40pm_

Perhaps this is mainly an omdoc issue?

> I wonder whether the example of attributing a OpenMath object with a visual rendering is still up to date,

I dont see any such example in the OM2 spec? So I'm not sure where this example is, however I think visual rendering is still a reasonable attribution example, mathml presentation was available for OM2 as well. so nothing really has changed here has it?
If it was a reasonable example before, it should be reasonable now.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 25-Nov-2008 12:47pm_

Replying to [comment:1 david]:

> Perhaps this is mainly an omdoc issue?
> While _our'' use cases come from OMDoc, my question was rather about reasonable uses of attribution in ''any_ OpenMath application.
> 
> > I wonder whether the example of attributing a OpenMath object with a visual rendering is still up to date,
> > I dont see any such example in the OM2 spec? So I'm not sure where this example is
> > There is no proper example, it's just mentioned with a few words:
> > 
> > ```
> > OpenMath objects can be attributed with OpenMath foreign objects, which are containers for
> > non-OpenMath structures. For example a mathematical expression could be attributed with
> > its spoken or visual rendering.
> > ```

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:57am_

This is still a valid concern IMHO, albeit of minor significance, as it's merely asking for an _example_ to be included in the standard.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 17-May-2014 1:54pm_

Typical task for the altenc CD symbols, I'd say.

**Comment by kohlhase** [comment]
not a priority anymore
