### ISSUE TITLE
OMR examples false

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#104]
_migrated from Trac, where originally posted by **kohlhase** on 30-Jan-2009 12:26am_

Dan Roozemond from the SCIENCE project spotted an error in the OpenMath2 Spec: The text and RNC say that `OMR` takes a `href` attribute while the examples all use a `xref` attribute. So `xref="foo"` should be changed to `href="#foo"`.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 5-Dec-2009 2:30pm_

The spec should also spend a few words on the usage of **href** for parallel markup; cf. the corresponding section in the MathML spec.  According to the MathML 3 spec one can use parallel markup in either direction: `m:*/**xref**` (here it's xref!) pointing to `om:*/**id**`, or otherwise `om:*/**href**` pointing to `m:*/**id**`.  This is intended; both cases should shortly be mentioned in the OM spec.

**Comment by kohlhase** [comment]
we have a current issue on this.
