### ISSUE TITLE
abstract CDGroups and CDSigs

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#105]
_migrated from Trac, where originally posted by **kohlhase** on 30-Jan-2009 2:40am_

In MathML2 we abstracted from the concrete OCD format to the concept of an abstract CD which alllowed other mechanisms like XHTML+RDFa or MathML or OMDoc. We should probably do the same to the CDGroups now that they may be  coming into great prominence in MathML3 and while we are at it also the CDSig files.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:35pm_

rescheduling.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/26
