### ISSUE TITLE
Binary encoding is bigendian

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#107]
_migrated from Trac, where originally posted by **jhd** on 15-Apr-2009 2:37am_

Not, as it says in OM2, little-endian. All the text and examples in OM2 are correct apaprt from that one word. Reported by Martin Weber (NIST).

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 1:33pm_

this is related to #114, merge these two?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 15-May-2014 12:20pm_

Replying to [comment:1 kohlhase]:

> this is related to #114, merge these two? 

Upon closer examination, they are distinct. This one is about the binary encoding. #114 is about OMF elements in the XML encoding. There may be a common cause (one terminologically confused author) for both, but they are technically unrelated.

**Comment by JamesHDavenport** [comment]
Aimed to fix in OM 2.0r1

**Comment by kohlhase** [comment]
This has been taken care in OM 2.0r1
