### ISSUE TITLE
typo in OMSTD2.0 chapter

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#108]
_migrated from Trac, where originally posted by **kohlhase** on 27-Apr-2009 11:52pm_

The third example in Chapter 5.2 in the OM2 standard has the line 

```
<semantics xmlns="xmlns="http://www.w3.org/1998/Math/MathML">
```

whiich is a typo.

**Comment by tkw1536** [comment]
Fixed in revision 1 draft

**Comment by physikerwelt** [comment]
I think the bug should not be closed before the draft was finalized.
