### ISSUE TITLE
Roles and Complience

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#109]
_migrated from Trac, where originally posted by **kohlhase** on 27-Apr-2009 11:56pm_

The compliance chapter (chapter5) does not talk about roles at all. I do not remember whether that was intentional, but the restrictions in front are useless if there is no compliance consequence from them. 

Even if we do not want to mention roles in Chapter5, we should say so and why.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 17-May-2014 2:20pm_

This was mentioned during yesterday's skype meeting, was it not? (I don't see it in the notes of the meeting, however, so I may be wrong.)

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/25
