### ISSUE TITLE
Mixed content for textual bits in CD descriptions

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#11]
_migrated from Trac, where originally posted by **polx** on 6-Nov-2007 11:12pm_

It has been our experience that simple text is too often too small  
to express and that the obvious web-rendering of CDs should take  
advantage of links imperatively.

They should be possible within properties, examples, and comments.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 8-Nov-2007 12:40pm_

We were discussing opening up the text format for CDs at the MathML F2F, and David cautioned that we need a short ASCII (i.e. without MathML) description of a symbol that can be displayed in a tooltip or so;\

We agreed that we should have two fields:
1. <description> with short simple ASCII/UniCode text  
2. <discussion> with a subset of XHML+MathML

I have made a first suggestion in an experimental RNC for MCDs. That could then go into an extended CD format for OM3.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 23-Jan-2008 7:32am_

We have <description> and <discussion> from the MathML CDs, and I have experimentally introduced a <Title> field to CDS for the ASCII stuff, this name seems better.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 23-Jan-2008 7:44am_

David Carlisle had suggested to take the inline model of XHTML2 for this, I guess that he means the following modules 
- [XHTML Text Module](http://www.w3.org/TR/xhtml2/mod-text.html#s_textmodule)
- [XHTML Hypertext Module](http://www.w3.org/TR/xhtml2/mod-hypertext.html#s_hypertextmodule)
- [XHTML List Module](http://www.w3.org/TR/xhtml2/mod-list.html#s_listmodule)
- [XHTML Core Attributes Module](http://www.w3.org/TR/xhtml2/mod-core.html#s_coremodule)
- [XHTML Hypertext Attributes Module](http://www.w3.org/TR/xhtml2/mod-hyperAttributes.html#s_hyperAttributesmodule)
- [XHTML I18N Attribute Module](http://www.w3.org/TR/xhtml2/mod-i18n.html#s_i18nmodule)
- [XHTML Image Module](http://www.w3.org/TR/xhtml2/mod-image.html#s_imagemodule)
- [XHTML Object Module](http://www.w3.org/TR/xhtml2/mod-object.html#s_objectmoduley)

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **polx** on 23-Jan-2008 9:35am_

Where would you put OpenMath inside there?

It has to be there, I think.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 23-Jan-2008 3:39pm_

you are right, I had forgotten, we need to extend the inline model by OpenMath and MathML here.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **david** on 29-Jan-2008 1:14am_

Replying to [comment:11 kohlhase]:

I'm not sure that OM and MML should be inlined into he xhtml (not necessarily against it) traditionally openmath has been restricted to specific CD fields that were just openmath (FMP and friends) with descriptive text being in fields that did not have any OM (Description and friends).

We could allow a richer text markup (eg xhtml) without necessarily allowing OM.
CDUses and general consistency checking gets harder if we allow unconstrained use of OM in text fields. (Although some things might be easier to express...)

As for the content model I'd probably use less than all the models you listed in comment #8, no object for a start. Maybe just start small, I'd probably allow p (although it's not inline) because otherwise it's hard to make long comments without falling back on blank line syntaxes, and then perhaps just b i br lists and a.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 30-Jan-2008 4:47am_

Replying to [comment:12 david]:

> Replying to [comment:11 kohlhase]:
> 
> I'm not sure that OM and MML should be inlined into he xhtml (not necessarily against it) traditionally openmath has been restricted to specific CD fields that were just openmath (FMP and friends) with descriptive text being in fields that did not have any OM (Description and friends).
> We talked about this before and it seemed that there were voices (Paul's, mine,...) that wanted to have some kind of Math in descriptive fields so that we can really say what we mean mathematically. The view is that descriptive fields should be rigorous math like in textbooks. 

There were voices (your's,...) that were worried about universally being able to display CD material in e.g. tooltips,... 

I thought that your suggestion to have two kinds of descriptive fields 
- one short one for tooltips without embedded math
- one longer one for rigorous math vernacular with embedded mobj
  (the first one being mandatory, the second one being optional) was a very sensible compromise in this situation. 

> We could allow a richer text markup (eg xhtml) without necessarily allowing OM.
> agreed, these are independent. 
> CDUses and general consistency checking gets harder if we allow unconstrained use of OM in text fields. (Although some things might be easier to express...)
> I am not very worried about this, XPath and XSLT are really quite powerful :-)
> 
> As for the content model I'd probably use less than all the models you listed in comment #8, no object for a start. Maybe just start small, I'd probably allow p (although it's not inline) because otherwise it's hard to make long comments without falling back on blank line syntaxes, and then perhaps just b i br lists and a.
> I probably agree with dropping object, but I think that image should be in there. Of course you could use <mglyph> now, but I would consider that as cheating semantically. 
> Another thing I realize, I think that we will need tables, and that somehow got dropped from my list above.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:06pm_

rescheduling

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 19-May-2014 2:38pm_

See also #145 (Allow OMOBJ in OMCD texts).

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/20
