### ISSUE TITLE
Wrong svn certificate or access permissions

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#112]
_migrated from Trac, where originally posted by **clange** on 11-Nov-2009 9:57pm_

I cannot update:

```
$ svn up
Error validating server certificate for 'https://svn.openmath.org:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
 - The certificate hostname does not match.
 - The certificate has expired.
Certificate information:
 - Subject: EMAILADDRESS=dm-support**dfki**.de, CN=www.lms.saarlernnetz.de, OU=SLN, O=DFKI GmbH, L=Saarbruecken, C=DE
 - Valid: from Fri Nov 23 14:59:53 CET 2007 until Sat Nov 22 14:59:53 CET 2008
 - Issuer: EMAILADDRESS=dm-support**dfki**.de, CN=www.lms.saarlernnetz.de, OU=SLN, O=DFKI GmbH, L=Saarbruecken, C=DE
 - Fingerprint: b2:54:92:37:a9:15:b1:40:ea:df:59:6e:d9:6d:11:d8:18:8d:aa:fd
(R)eject, accept (t)emporarily or accept (p)ermanently? p
svn: PROPFIND of '/': 405 Method Not Allowed (https://svn.openmath.org)
```

Similar problems for other means of access.  Opening the URL in the browser leads me to [this Apache documentation](https://svn.openmath.org/en/index.html).

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **polx** on 11-Nov-2009 10:33pm_

Christoph,

at this stage, I cannot offer you anything else than non https checkout.

paul

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 11-Nov-2009 10:40pm_

Replying to [comment:1 polx]:

> at this stage, I cannot offer you anything else than non https checkout.
> Oh, thanks, I didn't even know that plain http access is possible.  Maybe you should announce that once more on the mailing list.

BTW, http access tells me that there is still Subversion 1.0.8 running.  Will it eventually be possible to upgrade?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:42am_

Who is now running the SVN server?  This might be obsolete now.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 19-May-2014 1:02pm_

I think it was mentioned in the meeting on Friday (2014-05-16) that James needs SVN access to sort out some issues with CDs, so even if it's not the same issue, a very similar issue persists.

If we want to make more use of Trac, I suspect The Right Thing would be to have a blocker level ticket for that SVN access issue (this one or a new one), and mark all the minor CD file issues as depending on that. But that could be unnecessary administration.

**Comment by kohlhase** [comment]
we are using github now.
