### ISSUE TITLE
Why is cddefinition width: 70em?

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#113]
_migrated from Trac, where originally posted by **lars_h** on 14-Dec-2009 11:56am_

The XHTML renderings of OM CDs, such as http://svn.openmath.org/OpenMath3/cd/MathML/set1.xhtml, apparently use (among other things) http://svn.openmath.org/OpenMath3/cd/MathML/omcd.css for styling. That file says that a div.cddefinition is width: 70em, which seems very unnecessary.

Practically, this fixes a width for div.cddefinition elements (the "boxes" in the rendered page), quite contrary to the general principle that the width of paragraphs of text in web pages should adapt to the width of the viewport in which they are displayed. This thus deprives the user of some control, for no apparent reason.

Bear in mind that 70em is a rather large width —  certainly larger than what fits on my old laptop at default text size — that corresponds to maybe 140–200 characters per line. Manuals of typography generally recommend 70–80 characters as optimal for reading. By not specifying a width, you would allow users to resize their browser windows to a line width of their preference.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 15-May-2014 12:12pm_

This may have resolved itself over time, but probably more by accident than by design.

Upon closer examination, I think this pointed at problem with the OpenMath3 wiki, which seems to be dead. Or is it just picky about which browsers people can use?

The OM2 CDs (e.g. http://www.openmath.org/cd/set1.xhtml) also link to omcd.css, but that file is not found, so it doesn't matter. And the formatting is so oldschool that it doesn't use <div> elements with class attributes, so it wouldn't matter if an omcd.css with this setting was found.

**Comment by kohlhase** [comment]
obsolete now.
