### ISSUE TITLE
Endianness of OMF

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#114]
_migrated from Trac, where originally posted by **lars_h** on 19-Dec-2009 7:08pm_

The OM standard (version 2.0 and current omstd30.xml in SVN) speaks about the hex attribute of an OMF being in least significant byte ordering. However, all examples given rather seem to be in _most_ significant byte ordering.

For example, 1.0e-10 as an IEEE binary64 number is claimed to be hex="3DDB7CDFD9D7BDBB". From e.g. http://en.wikipedia.org/wiki/Double_precision_floating-point_format, we can learn that the sign bit is bit 63, and that it must be 0 on account of this being a positive number. This is consistent with the example being in MSB order, as bit 63 is then worth 8 in the first digit position, and that digit is only 3. It is not at all consistent with the example being in LSB order, since that would make bit 63 worth 8 in the second last digit position, thus making the sign bit 1 since that digit is B.

In more detail, the MSB interpretation is that the above hex data encodes the number

```
$$
  (-1)^0 \cdot 2^{(\mathtt{3DD})_{16}-1023} \cdot (\mathtt{1.B7CDFD9D7BDBB})_{16},
$$
```

which indeed evaluates to 1.0e-10, whereas the LSB interpretation would be

```
$$
  (-1)^1 \cdot 2^{(\mathtt{3BB})_{16}-1023} \cdot (\mathtt{1.DD7D9DF7CDB3D})_{16},
$$
```

which rather evaluates to -6.3195366849202934e-21.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 1:34pm_

this is related to #107, merge these issues?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 25-Feb-2011 4:13pm_

Replying to [comment:2 kohlhase]:

> this is related to #107, merge these issues?

Yes, it appears I made a duplicate. Both reports contain information not in the other, however.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 15-May-2014 12:23pm_

Replying to [comment:3 lars_h]:

> Replying to [comment:2 kohlhase]:
> 
> > this is related to #107, merge these issues?
> 
> Yes, it appears I made a duplicate. Both reports contain information not in the other, however.

Correction of myself: This is _not_ a duplicate. #107 is about the binary encoding. This one is about OMF elements in the XML encoding. There may be a common cause (one terminologically confused author) for both, but they are technically unrelated.

**Comment by kohlhase** [comment]
this has been addressed in the first edition of OM2
