### ISSUE TITLE
Publish OpenMath ontology under its namespace URI=URL

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#117]
_migrated from Trac, where originally posted by **clange** on 6-Apr-2010 2:56pm_

As a part of the overall effort of publishing the OpenMath CDs as linked data (cf. #116), we need the OpenMath ontology to be available at its namespace URI/URL http://www.openmath.org/ontology# .

This is a two-step process:
1. make the file that is currently at http://svn.openmath.org/OpenMath/OpenMath3/owl/openmath.owl available as http://www.openmath.org/ontology/openmath.owl.  **Paul**, could you please tell me (either here or by e-mail) how to add an "/ontology" directory to the homepage?  Do I have to modify build.xml?
2. according to http://www.w3.org/TR/swbp-vocab-pub/, rewrite http://www.openmath.org/ontology# into the above URL using the following lines in the Apache configuration:

```
RewriteEngine On
RewriteRule ^/ontology$ /ontology/openmath.owl [L]
```

 **Paul**: Is that possible with our Apache?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:38am_

I would still be willing to finish publication of the OpenMath CDs as linked data, which includes publishing the vocabulary of these data (a.k.a. ontology, i.e. an RDF encoding of the OpenMath CD language), which is what this ticket is about.

I will not easily be able to make any progress on this if it's not possible to get an account on the web server.  Which is where now?  Still at DFKI?

**Comment by kohlhase** [comment]
we are not pursuing ontology at the moment.
