### ISSUE TITLE
Serve OpenMath CDs as ocd, XHTML (and RDF?) from Cool URIs

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#120]
_migrated from Trac, where originally posted by **clange** on 7-Apr-2010 7:49pm_

The canonical URI of an OpenMath symbol is `cdbase / cd # name`.  For the #116 agenda/scenario it is required that symbols be retrievable from their URI = URL.  Consider the symbol with the URI http://www.openmath.org/cd/arith1#plus.  So far information about it is available from the following URLs:
- http://www.openmath.org/cd/arith1.ocd#plus (OpenMath CD format, [ticket:119 assuming appropriate xml:id attributes])
- http://www.openmath.org/cd/arith1.xhtml#plus (XHTML, there we already have the right IDs :-)
- http://www.openmath.org/cd/arith1.rdf#plus (RDF/XML: not yet, but easily possible)
  The linked data best practices, particularly the ["Cool URI" design principles](http://www.w3.org/TR/cooluris/) require one "cool" URI for everything:  http://www.openmath.org/cd/arith1#plus.  The client accesses that URI = URL and in the HTTP Accept header requests the desired MIME type: OpenMath ([ticket:106 to be specified!!]), text/html or application/xhtml+xml for XHTML, or application/rdf+xml for RDF/XML, or whatever else (will reasonably default to OpenMath).

**Paul**, similar question as in #117: It is easily possible to set that up in Apache.  Is it also easily possible to set it up in _our_ Apache?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 1:00am_

I would be willing to finalize the publication of the CDs (including the ocd, html and rdf formats) as linked open data, but I would need access to the web server where they happen to be.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **polx** on 20-May-2014 6:18pm_

Christoph, you need to assign this to Jan Willem Knopper.
I don't see him as assignable person.
We should write him.
Agree?

paul

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 2-Jun-2014 11:42am_

Replying to [comment:2 polx]:

> Christoph, you need to assign this to Jan Willem Knopper.
> I don't see him as assignable person.
> We should write him.

Thanks, Paul, for pointing out.

**Jan** Willem, I've put your email on Cc for this ticket.  For the [reassignment to you to work](http://trac.edgewall.org/wiki/TracTickets#Assign-toasDrop-DownList) could you please once log into this Trac, and then assign this ticket to you?

BTW, this Trac knows you by the username `jwk`, but using your old STACK email address.  You might want to tell Trac your current address as well.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jwk** on 2-Jun-2014 11:47am_

I've logged on, but I don't seem to be able to claim this ticket

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 2-Jun-2014 8:33pm_

Replying to [comment:4 jwk]:

> I've logged on, but I don't seem to be able to claim this ticket
> No idea; let's resolve it with Michael or their group's sysadmin.

**Comment by kohlhase** [comment]
I think we are doing that now.
