### ISSUE TITLE
Check whether OpenMath functions are the same as in DLMF

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#122]
_migrated from Trac, where originally posted by **clange** on 17-Jul-2010 8:55pm_

The definitions of the following symbols from the OpenMath CDs in http://svn.openmath.org/OpenMath/www/cdfiles2/cd refer to the A&S book:
- nums1#e
- nums1#gamma
- transc1#log
- transc1#ln
- transc1#exp
- transc1#sin
- transc1#cos
- transc1#tan
- transc1#sec
- transc1#csc
- transc1#cot
- transc1#sinh
- transc1#cosh
- transc1#tanh
- transc1#sech
- transc1#csch
- transc1#coth
- transc1#arcsin
- transc1#arccos
- transc1#arctan
- transc1#arcsec
- transc1#arccsc
- transc1#arccot
- transc1#arcsinh
- transc1#arccosh
- transc1#arctanh
- transc1#arcsech
- transc1#arccsch
- transc1#arccoth
- transc3#log
- transc3#arcsin
- transc3#arcsinh
- transc3#arccosh
- transc3#arctanh
- transc3#arcsech
- transc3#arccsch
- transc3#arccoth
- Note: some of the transc3 functions refer to A&S, others don't
- (**James**, if you want, you can mark functions that have been checked in this list, e.g. ~~strike them out~~)
  James will check whether their DLMF definitions have the same properties as the OpenMath CD definitions, i.e. whether DLMF and the CDs describe the same functions/constants.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 1:00am_

Still a valid concern IMHO

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/CDs/issues/28
