### ISSUE TITLE
Clean up duplicate XSLT stylesheets

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#123]
_migrated from Trac, where originally posted by **clange** on 29-Jul-2010 6:20pm_

```
~/svn/openmath.org$ svn info
Path: .
URL: http://svn.openmath.org/OpenMath
Repository Root: http://svn.openmath.org/OpenMath
Repository UUID: f6c7b38d-9334-0410-b102-eeb4acc4338b
Revision: 1173
Node Kind: directory
Schedule: normal
Last Changed Author: polx
Last Changed Rev: 1173
Last Changed Date: 2010-07-09 19:08:58 +0200 (Fri, 09 Jul 2010)

~/svn/openmath.org$ find . -name arith1.xsl
```

Some of them must be orphaned and should be cleaned up.  I put this up for discussion among the infrastructure group.

```
./www/cdfiles2/xsl/arith1.xsl
```

These seem to be the ones that are most actively maintained.

```
./www/cdfiles2/xsl-old/arith1.xsl
```

An old backup of the former ones?

```
./www/standard/omxsl/arith1.xsl
```

Did they have an official status as a part of the OM standard?  I don't think so.

```
./OpenMath3/xsl/cd/arith1.xsl
```

Part of the discussion that we've already had on the infrastructure list, on what future the experimental MathML/OpenMath 3 CDs should have.

```
./formerCVS/omxsl/arith1.xsl
```

Seems to be an old archival copy; do we need it?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **david** on 30-Jul-2010 10:35am_

On 29/07/2010 19:20, OpenMath wrote:

> #123: Clean up duplicate XSLT stylesheets

As a general rule I'm wary about "cleaning up" the source control, that's arrasing history. (stopping things appearing in the http://www/openmath.org view is a different matter. (using email as I couldn't log on to trac, perhaps the email interface will add this automatically to the ticket..)

>  ~/svn/openmath.org$ find . -name arith1.xsl
>  }}}
>  Some of them must be orphaned and should be cleaned up.  I put this up for
>  discussion among the infrastructure group.
>  {{{
>  ./www/cdfiles2/xsl/arith1.xsl
>  }}}
>  These seem to be the ones that are most actively maintained.
>  {{{
>  ./www/cdfiles2/xsl-old/arith1.xsl
>  }}}
>  An old backup of the former ones?
>  {{{
>  ./www/standard/omxsl/arith1.xsl
>  }}}
>  Did they have an official status as a part of the OM standard?  I don't
>  think so.

I seem to remember at one point we were considering using the "xhtml view" of the CDs in the standard and these xsl were then part of the build system for the standard, but in the end we went with the colour-coded xnml souce view of the CDs in the standard so I don't think these are used in the end.

while checking this I note the normative multi-file openmath standard has broken links to the CDs (the single file version works)

http://www.openmath.org/standard/om20-2004-06-30/omstd20html-A.xml#arith1.ocd

should be

http://www.openmath.org/standard/om20-2004-06-30/omstd20html-a.xml#arith1.ocd

(with a lowercase a) I'm sure that used to work, probably the old server had some built in redirect rules to be effectively case insensitive. We should probably add the redirect to the server here rather than changing the standard text at this point.

>  {{{
>  ./OpenMath3/xsl/cd/arith1.xsl
>  }}}
>  Part of the discussion that we've already had on the infrastructure list,
>  on what future the experimental MathML/OpenMath 3 CDs should have.
>  {{{

Yes as Ive noted before we shoudl probably lose  ./OpenMath3 in its present form ffom www.openmath.org, however we should not lose the svn history of the work that was done there. (Also that holds the current versions of the om <-> content mathml stylesheets, although I'll probably move those at some point

>  ./formerCVS/omxsl/arith1.xsl
>  }}}
>  Seems to be an old archival copy; do we need it?

I guess this is an artifact of the cvs-svn conversion that can go?

David

---

The Numerical Algorithms Group Ltd is a company registered in England
and Wales with company number 1249803. The registered office is:
Wilkinson House, Jordan Hill Road, Oxford OX2 8DR, United Kingdom.

This e-mail has been scanned for all viruses by Star. The service is
powered by MessageLabs. ________________________________________________________________________

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 30-Jul-2010 12:59pm_

Replying to [comment:1 david]:

> As a general rule I'm wary about "cleaning up" the source control, that's arrasing history. 
> OK, right, I should have said that by "cleaning up" I did not necessarily mean "deleting", but rearranging things.  With the current state of things, anyone new to OpenMath (probably not even old OpenMath users) who checks out the svn would have a hard time finding out which of the many XSLTs he should actually use.
> (stopping things appearing in the http://www/openmath.org view is a different matter. (using email as I couldn't log on to trac, perhaps the email interface will add this automatically to the ticket..)
> It works.
> I seem to remember at one point we were considering using the "xhtml view" of the CDs in the standard and these xsl were then part of the build system for the standard, but in the end we went with the colour-coded xnml souce view of the CDs in the standard so I don't think these are used in the end.
> Aren't even the colour-coded XML sources just examples?  I'm asking because only a few CDs are listed that way in the appendix.  In any case the XSLTs are not mentioned in the standard, but still they are a valuable part of the "unofficial software distribution" we maintain at openmath.org.
> while checking this I note the normative multi-file openmath standard has broken links to the CDs (the single file version works)
> 
> http://www.openmath.org/standard/om20-2004-06-30/omstd20html-A.xml#arith1.ocd
> 
> should be
> 
> http://www.openmath.org/standard/om20-2004-06-30/omstd20html-a.xml#arith1.ocd
> 
> (with a lowercase a) I'm sure that used to work, probably the old server had some built in redirect rules to be effectively case insensitive. We should probably add the redirect to the server here rather than changing the standard text at this point.
> **Paul**, is that something you can fix?
> Yes as Ive noted before we shoudl probably lose  ./OpenMath3 in its present form ffom www.openmath.org
> IIRC it's not part of the web pages at www.openmath.org in any way, is it?  So the only thing to be done would be e.g. renaming the svn directory or putting a readme file there saying that it is experimental or for archival purposes.
> however we should not lose the svn history of the work that was done there. (Also that holds the current versions of the om <-> content mathml stylesheets, although I'll probably move those at some point
> Of course.  Note that when you delete something in svn the history is also preserved, but of course no longer in an obvious way.  So I'd say that we could probably _relocate_ some directories, i.e. out of the sight of an average visitor to the repository.
> 
> >  ./formerCVS/omxsl/arith1.xsl
> > I guess this is an artifact of the cvs-svn conversion that can go?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **david** on 30-Jul-2010 1:14pm_

On 30/07/2010 13:59, OpenMath wrote:

>  OK, right, I should have said that by "cleaning up" I did not necessarily
>  mean "deleting", but rearranging things.  With the current state of
>  things, anyone new to OpenMath (probably not even old OpenMath users) who
>  checks out the svn would have a hard time finding out which of the many
>  XSLTs he should actually use.

agreed.

>  Aren't even the colour-coded XML sources just examples?  I'm asking
>  because only a few CDs are listed that way in the appendix.
> arith1 is there as an example but meta and error are a bit different as they are  effectively part of the standard as they are used (if i recall correctly) to define the CD format and error handling behaviour respectively.

  In any case

>  the XSLTs are not mentioned in the standard, but still they are a valuable
>  part of the "unofficial software distribution" we maintain at
>  openmath.org.

the ones in the main omxsl are, but I think the ones in the standard area are just a frozen snapshot of them intended to be part of the build of the standard document, so the standard document text didn't change if we changed the CD formatting. But they ended up not being used. I think that's the history anyway, although it's a long time ago:-)

>  IIRC it's not part of the web pages at www.openmath.org in any way, is it?

yes:

http://www.openmath.org/OpenMath3/

>  So the only thing to be done would be e.g. renaming the svn directory or
>  putting a readme file there saying that it is experimental or for archival
>  purposes.
> 
> >  however we should not lose the svn history of the work that was done
> >  there. (Also that holds the current versions of the om<->  content mathml
> >  stylesheets, although I'll probably move those at some point
> >  Of course.  Note that when you delete something in svn the history is also
> >  preserved, but of course no longer in an obvious way.  So I'd say that we
> >  could probably _relocate_ some directories, i.e. out of the sight of an
> >  average visitor to the repository.

agreed.

David

---

The Numerical Algorithms Group Ltd is a company registered in England
and Wales with company number 1249803. The registered office is:
Wilkinson House, Jordan Hill Road, Oxford OX2 8DR, United Kingdom.

This e-mail has been scanned for all viruses by Star. The service is
powered by MessageLabs. ________________________________________________________________________

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 1-Aug-2010 7:35am_

adding myself in the cc.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 1:01am_

I could imagine that nothing about this has changed, but for lack of time I'd like to focus my contributions on linked data rather than XSLT, so I'm not volunteering for this clean-up task.

**Comment by kohlhase** [comment]
we have a completely now repository structure now.
