### ISSUE TITLE
CD versioning probably not compatible with CD URIs

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#126]
_migrated from Trac, where originally posted by **clange** on 20-Aug-2010 8:16pm_

This ticket assumes that there is some canonical way of _retrieving'' a CD.  That ''could_ be the linked data style of publishing CDs for download from their canonical URI.  If we don't like that, it could be any other mode of retrieval, but to facilitate the explanations below, I will assume linked data.

First the relevant facts from the standard:
1. CDs have URIs of the form `CDBase / CDName`.
2. CDs and CDGroups have versions.
3. A CDGroup can optionally refer to a particular version of a CD
4. An OpenMath-compliant application must say what version (major + minor) of a CD or of a CDGroup (major) it supports.

It seems reasonable to expect that the "latest" version of a CD is immediately available from its URI.  But what if an application supports an earlier version of a CD?  Where would that earlier version be retrieved from, in case someone (the application itself, the maintainer of the application's code, etc.) wants to look into it?

I guess we need to specify some way of retrieving a specific version of a CD.  I could imagine a parameter to the URI=URL of a CD, e.g. `http://www.openmath.org/cd/arith1?version=major&revision=minor`.

A possible spec text:

> If some system needs a single identifier to talk about a (CD,version) pair, it should use the URI `http://www.openmath.org/cd/arith1?version=major&revision=minor`".  CD authors MAY publish versions of their CDs in such a way that they are retrievable by dereferencing these URIs.  In that case, the URI without version parameters always refers to the latest available version.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **polx** on 21-Aug-2010 9:44am_

Christoph,

I think such a scheme should be as easy to implement as possible and should be supported by static file-based serving.

A URL parameter is hard to support by such as Apache (and that's used on www.openmath.org).

A name suffix is much easier but I guess it adds restrictions to the core naming.

paul

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 1:03am_

I still tend to think that this is a conceptual flaw in the standard: the standard specifies versions of CDs, but not how to retrieve them.

**Comment by kohlhase** [comment]
this is moved to https://github.com/OpenMath/OMSTD/issues/43
