### ISSUE TITLE
Make CDSignatures or Signature use cdbase

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#128]
_migrated from Trac, where originally posted by **clange** on 23-Aug-2010 10:43pm_

An old issue remembered (discussed on the mailing list in 2008):  Within the OpenMath 2.0 standard one cannot write a signature dictionary for a CD that does not have the default cdbase http://www.openmath.org/cd, as CDSignature only has a `cd` attribute.  It needs a `cdbase` attribute as well.

Alternatively, if we want to make individual `<Signature>` elements self-contained (e.g. for copy-paste scenarios), we might want to use `<Signature cdbase="..." cd="..." name="...">` and maybe only use the `cdbase` and `cd` of the `CDSignature` root element as a fallback.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 1:06am_

Still a valid concern IMHO.  Not sure who is _using_ signatures nowadays, but as long as we continue having them in the standard (and I don't see a reason to drop them), they should work.  This issue points out something that's broken about them.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 19-May-2014 5:14pm_

So: the problem is that there is no way to know for sure, given a signature dictionary, _which'' content dictionary it is providing a signature for, since it only keeps track of the cd ''name_ (using the cd attribute of the CDSignatures element) and not the cdbase?

It seems to me that for people writing a content dictionary with a non-default cdbase, it would still be more likely that they would use one of the standard type systems than of their own making, so the OMOBJ elements should probably not inherit a cdbase specified in CDSignatures.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 2-Jun-2014 11:30am_

Replying to [comment:2 lars_h]:

> So: the problem is that there is no way to know for sure, given a signature dictionary, _which'' content dictionary it is providing a signature for, since it only keeps track of the cd ''name_ (using the cd attribute of the CDSignatures element) and not the cdbase?
> That's exactly the problem, and as a measure against this I proposed adding a `**cdbase**` attribute to `Signature`.  Or, for a more sophisticated approach, see the second paragraph of the Description above.
> It seems to me that for people writing a content dictionary with a non-default cdbase, it would still be more likely that they would use one of the standard type systems than of their own making,
> To my understanding the `Signature` element is independent from the concrete choice of a type system, …
> so the OMOBJ elements should probably not inherit a cdbase specified in CDSignatures.
> … and inside an `OMOBJ`, e.g. for `OMS` elements, the `cdbase` situation is that you have to specify it, or otherwise it falls back to `http://www.openmath.org/cd`.  Which makes sense IMHO.  The CD base of an `OMOBJ` that specifies the type of some symbol `S` (or, more specifically: the CD base of the symbols used to construct that type) need not be the same as the CD base of `S`.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/34
