### ISSUE TITLE
Subsumption relation between symbols

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#13]
_migrated from Trac, where originally posted by **polx** on 6-Nov-2007 11:15pm_

I would wish simple "sub-kind" relation between symbols.

I know types and other artifacts can play a role here but a simple  
sub-kind appears more effective to me and could have relatively  
immediate applications to "semi-public-CDs"

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 8-Nov-2007 12:48pm_

I do not understand what you have in mind, could you please give an example?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:34pm_

rescheduling

**Comment by kohlhase** [comment]
not doable at the level of OpenMath CDs
