### ISSUE TITLE
] range & image in fns1

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#130]
_migrated from Trac, where originally posted by **kohlhase** on 26-Aug-2010 10:53am_

I am trying to get things organized, there was a complaint by Bruce Miller about naming in `fns1.ocd`; see also #43.

Hi all;
   In trying to answer a student's question
about the difference between range and image
(& implicitly codomain) ... and rather stumbling...

Math question:
My naive understanding was that the image is
_exactly_ the set of values produced by a function
over some domain (or subset of the domain)
--- no more, no less.
And, that range is allowed to be some larger set
than the image if it is more convenient for some
purposes (eg continuous, convex, whatever) ...

Is that correct, and are there any formal conditions
on how a range is defined w.r.t an image?
Or is it simply expanded to get whatever desired properties?

OpenMath question:
  The description, CMP & FMP for the symbol range at
     http://www.openmath.org/cd/fns1.xhtml#range
are contradictory.  The description ("range ... merely
required to contain the image") is consistent
with my understanding (such that it is).

However, the CMP says that the range is a subset of
the image, while the FMP goes further saying that
the range is a proper subset (to the extent the
implied "proper" is significant).

Shouldn't the FMP be:
   image(f) \subseteq range(f)

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 26-Aug-2010 10:54am_

Arjeh Cohen answered to that:

that is, the answer is yes. It seesm liek very few people have
actually checked what was written. As for the definition of "range",
more clarity is given in fns3, which I (think I) wrote a couple of years ago.
Reading the http://www.openmath.org/cd/fns3.xhtml#range version,
I see several typos that have never been repaired, like "aplied" and "stes".

**Comment by kohlhase** [comment]
this is now folded into https://github.com/OpenMath/CDs/issues/4 closing here.
