### ISSUE TITLE
Disambiguate CDGroup/CDName

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#131]
_migrated from Trac, where originally posted by **clange** on 26-Aug-2010 11:04am_

CD groups have an important role in MathML 3 as they are the only means to use CD bases other than the default one (unless the host document format defines something else).  See http://lists.w3.org/Archives/Public/www-math/2010Jul/thread.html#msg19 for the background

The current documentation of `CDGroup/CDName` says:

> The text occurring in the CDName element corresponds to the name of a Content Dictionary in the CDGroup.

Suppose there is a CD `http://example.org/cd/mycd` (where this  URI is canonical, i.e. the CD has a `<CDBase>http://example.org/cd</CDBase>` and `<CDName>mycd</CDName>`.  Suppose we need to alias this CD (see the mail thread) to `mycd_alias` in the CD group, i.e.

```
<CDGroupMember>
  <CDName>mycd_alias</CDName>
  <CDURL>http://example.org/cd/mycd</CDURL>
</CDGroupMember>
```

In this situation the spec text "the name of a Content Dictionary in the CDGroup" is ambiguous.  Does it mean
- (the name of a CD) (in the CDGroup), i.e. the name of the CD as we like to call it for the purpose of this group – that would legalize aliasing
  Or does it mean
- (the name) (of a CD in the CDGroup), i.e. there is a CD that is member of this group, and the CD has a name (which is `mycd`), and the `CDGroup/CDName` element refers to that name – with that interpretation, aliasing would not work.

Therefore I suggest to disambiguate the spec text to make it work with MathML 3.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **david** on 26-Aug-2010 11:23am_

On 26/08/2010 12:04, OpenMath wrote:

> Therefore I suggest to disambiguate the spec text to make it work with
>  MathML 3.

yes, probably that would be a good interpretation:-)

---

The Numerical Algorithms Group Ltd is a company registered in England
and Wales with company number 1249803. The registered office is:
Wilkinson House, Jordan Hill Road, Oxford OX2 8DR, United Kingdom.

This e-mail has been scanned for all viruses by Star. The service is
powered by MessageLabs. ________________________________________________________________________

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 1:07am_

Still a valid concern IMHO.

**Comment by kohlhase** [comment]
https://github.com/OpenMath/OMSTD/issues/45
