### ISSUE TITLE
Abolish redundant CDSignatures/@type, or document best practices w.r.t. CDBase.

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#133]
_migrated from Trac, where originally posted by **clange** on 25-Oct-2010 5:24pm_

In 2008 I complained on the mailing list that `CDSignatures/**type**` is underspecified because it only refers to the type system by CD name but not by CD base, so using any type system whose CD base is not `http://www.openmath.org/cd` wouldn't work.  (See #128 for the related issue w.r.t. `CDSignatures/**cd**`.)

Well, but for `**type**` I wasn't right, as there are two possible workarounds:
1. make each per-symbol type signature refer to the type system by cdbase/cd/name OMS symbol references
2. make `**type**` refer to a CD group and use, in the CD group file, full CD URLs = URIs.
   By these two workarounds, a CDName-valued `**type**` is actually redundant.  So I'd say 
3. it should either be abolished
4. or in any case the best practice should be documented
   Note that, of course, by "best practice", in the age of linked data, I mean a web-scalable practice.  Not the "most frequently used practice" of ignoring CDBase :-P

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 26-Oct-2010 8:41pm_

It seems to me that this and 128 could sensibly be merged, as sorting out the whole inheritance mechanism for CDSignature. Another task fro the next OpenMath?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 1:08am_

Indeed I'd merge this with #128.

**Comment by kohlhase** [comment]
folded into https://github.com/OpenMath/OMSTD/issues/34
