### ISSUE TITLE
Specify or forbid whitespace normalisation

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#134]
_migrated from Trac, where originally posted by **clange** on 23-Jan-2011 9:15pm_

It is common OpenMath CD authoring practise (none that I personally like, but it exists) to assume whitespace normalisation, e.g. `<Name> foo </Name>` is assumed equivalent to `<Name>foo</Name>`.  However, [in contrast to MathML](http://www.w3.org/TR/MathML/chapter2.html#fund.collapse) this behaviour is not specified.  It should, or otherwise all CDs using that syntax are invalid.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 1:09am_

Still a valid concern IMHO

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/24
