### ISSUE TITLE
CD's CDBase declaration is mandatory

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#138]
_migrated from Trac, where originally posted by **clange** on 24-Jul-2011 11:14pm_

Currently the abstract CD specification (section 4.2) states that a CD must declare a CD base.  (In particular that means that, differently from symbols, there is no implicit fallback to `http://www.openmath.org/cd`.)

However the Relax NG currently says it's optional, so the Relax NG should be fixed, and, if necessary, the corresponding standard sections should be adapted.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 1:09am_

Still a valid concern IMHO

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 19-May-2014 12:03pm_

My position on this, after having thought about it, is that the abstract specification requirements in this area look like a rough first draft, whereas the RelaxNG schema represents a more balanced view, so I'd rather change the abstract specification to match the schema.

The most striking datapoint to illustrate this is probably the review date, which the abstract specification lists as mandatory but the schema makes optional. I would say it makes very little sense to specify a review date for a content dictionary unless you have established a concrete and solid review process, which to my knowledge is not the case for any extant content dictionary! Sure, it is possible to get the functional equivalent of "no review date" by specifying a review date in the past, but that is an awkward work-around rather than a clear expression of one's intent. The easy case should be that of a newly created content dictionary, and those will almost surely start out being experimental and highly fluid, so "no review date" is the sensible default.

I can see a case for making the Description mandatory. The case for making the CDBase mandatory falls somewhere between those for Description and CDReviewDate, but it is weakened by the fact that the CDBase is optional everywhere(?) else in the standard.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 2-Jun-2014 11:22am_

In any case the abstract CD specification should end up being a self-contained specification rather than a rough first draft.

Concretely for the CD base I could imagine one of the following:
- change the Relax NG to make its declaration mandatory
- or change the abstract CD specification to say that `http://www.openmath.org/cd` is the default if nothing else is specified.  Note however that this might not match the _practice_ of writing CDs.  People are lazy and tend to omit the CD base declaration, so having `openmath.org` as default would implicitly force CD authors to submit them to the OMSoc for review, to eventually have them published at `openmath.org` (because in the medium term the declared CD base should be coincide with the domain where the CD is published – even more so if we aim at linked data).  But again people are lazy and might forget about submitting their CDs for review.

About the review process we might want to open a separate discussion thread in a new ticket.  My view on this is that the Standard does specify a review process, but rather on a level that's too high for supporting a dedicated `CDReviewDate` syntax.

**Comment by kohlhase** [comment]
see https://github.com/OpenMath/OMSTD/issues/22
