### ISSUE TITLE
Symbol's default cdbase not specified correctly

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#139]
_migrated from Trac, where originally posted by **clange** on 24-Jul-2011 11:26pm_

When no CD base URI is given for a symbol, the CD base defaults to `http://www.openmath.org/cd` – well, we used to think so, but the standard does not say it.

The formal specification of OpenMath symbols in section 2.1.1 says that a symbol encodes … "(optionally) a Content Dictionary base URI".  It does not specify that, if such a URI is not given, it is taken from the nearest parent object that declares one, and if no CD base can be established that way, it defaults to `http://www.openmath.org/cd`.  (Note that Michael's favorite interpretation, i.e. that the language that embeds OpenMath, is free to define any other default value, is not covered either.)

The inheritance from the parent is specified in 3.1.2 for the concrete XML encoding and thus for the concrete case of XML parent elements.  The defaulting to `http://www.openmath.org/cd` is not specified there either.

Additionally Section 5.3 "Compliance -> Content Dictionaries" says, which confirms the _intent_ to have such a defaulting mechanism:

> Content Dictionaries available from the official OpenMath repository at www.openmath.org need only be referenced by name, other Content Dictionaries should be referenced using the CDBase and the CDName.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:43am_

Update: I think this is still a valid concern.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 27-May-2014 4:29pm_

Is this a duplicate of #83?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 2-Jun-2014 8:47pm_

Replying to [comment:2 lars_h]:

> Is this a duplicate of #83?
> Indeed it is, thanks for pointing out; I'll point #83 here as _this_ ticket is more precise.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/21
