### ISSUE TITLE
Container element for CMP & FMP, which can have a stable author-defined ID

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#140]
_migrated from Trac, where originally posted by **clange** on 24-Jul-2011 11:36pm_

Rationale: linking external datasets to the OpenMath CDs ([short example](http://trac.kwarc.info/krextor/wiki/OpenMathExtractionModule#Linkstoexternaldatasets), [detailed background](http://arxiv.org/abs/1006.4057))

[Proposed XML encoding, and example](http://trac.kwarc.info/krextor/wiki/OpenMathExtractionModule#Aproposalforreallystablepropertyidentifiers)

**Michael**, **James**, is that enough?  I'm not really keen on writing it up as a paper-like document, but I can elaborate the information on that page, if anything should still be unclear.

Suggested action:
1. extend the abstract CD specification accordingly, …
2. … as well as the XML reference encoding
3. adapt the CDs hosted on openmath.org accordingly

Issues to be discussed:
- do we want this explicit grouping of CMPs and FMPs (I think the previous discussion shows that we do)
- how to identify properties: relatively to the CD, or relatively to the symbol?
- what syntax to use for a property's ID?  (If we identify them per CD, we could also use `Property/**xml**:id`, but that would contradict the common OpenMath CD style.)
- in addition to the ID, do we also want to provide a human-readable description?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 1:10am_

I don't think I've ever proposed this as a _formal_ Standard Enhancement Proposal, but can we promote it into one?

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/42
