### ISSUE TITLE
Add dataset-level metadata to the CD RDF

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#142]
_migrated from Trac, where originally posted by **clange** on 12-Jul-2012 8:58am_

VoID, pointers to publications, etc.

(useful for http://datahub.io and inclusion into http://lod-cloud.net, should the cloud ever be updated again)

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:39am_

Would be nice, and I'd still be willing to do it.  However it would really only make sense if I were able to finalize the publication of the OpenMath CDs as linked open data (see #117).

**Comment by kohlhase** [comment]
not our priority at the moment.
