### ISSUE TITLE
[SEP]  Add Notation Definitions to OpenMath

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#144]
_migrated from Trac, where originally posted by **kohlhase** on 23-Sep-2013 8:27am_

OMDoc has a notion notation definitions, which works rather well. We should have something like that for OpenMath. I propose to adopt them for OpenMath Content Dictionaries.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/19
