### ISSUE TITLE
Bit numbers start at what?

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#146]
_migrated from Trac, where originally posted by **lars_h** on 7-Oct-2013 10:05am_

In the OM standard, bit numbers seem to start at 1 (rather than the more common 0), meaning bit k has a place value of 2^k-1^. It's probably not worth changing this, but some text should be added in strategic places to alert the reader about this convention being in effect. One such strategic place would be the beginning of the specification of the binary encoding, but I wouldn't rule out bit numbers being referenced also elsewhere in the text.

This is sort-of related to, but different from, the big-endian/little-endian confusion.

**Comment by lars-hellstrom** [comment]
Was this addressed in revision 1 of OM2?

**Comment by kohlhase** [comment]
yes, it was.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/18
