### ISSUE TITLE
Add OM3 committee members as Cc for the tickets discussed in the committee

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#149]
_migrated from Trac, where originally posted by **lars_h** on 19-May-2014 10:14am_

It could help the committee members to stay up to date on what is going on with the Trac tickets if they were explicitly Cc:ed on the issue. That is to say: tickets that are about issues that are _on topic_ for the committee, not just all tickets. On the other hand, most of the tickets still open seem to fall under that heading.

I'm filing this new ticket as an experiment on how that would work out.

Once a ticket has been created, I think you need to be owner (or Trac admin) to change any of the attributes, but when creating a new ticket I can add the whole bunch. I think.
- Skipping Michael since he'll end up owning the ticket anyway.
- Using email for Jan Willem and Chris, since I couldn't (easily) find a user name for them.
  But I won't do this for other new tickets I create unless we argee that it is a good idea.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 19-May-2014 10:38am_

I think that this is a good idea, but I think we can add the om3**openmath**.org list as a cc instead, that makes things more comprehensive.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 20-May-2014 10:15am_

I tried that with ticket #150, but it doesn't seem to have gotten through. The mail could be sitting and awaiting moderation, but using om3 as Cc address did not achieve the wanted effect of quickly informing everyone about what was going on.

I might be filing a few more tickets today, but I won't try adding a bunch of Cc:s there. In the meantime, another way of keeping track of activity can be a search such as the following:
https://trac.mathweb.org/OM3/query?status=assigned&status=new&status=reopened&col=id&col=summary&col=status&col=type&col=priority&col=milestone&col=component&col=changetime&desc=1&order=changetime
The main problem is that there doesn't seem to be a way of telling who did the last update (me or someone else), so it would be easy to miss a fast response.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 20-May-2014 2:07pm_

Actually, you are right on this, Note that there is also a RSS feed for this query (see at the bottom of the page) it is https://trac.mathweb.org/OM3/query?status=assigned&status=new&status=reopened&format=rss&col=id&col=summary&col=status&col=type&col=priority&col=milestone&col=component&col=changetime&desc=1&order=changetime
you can just subscribe to this in your preferred RSS reader (I use thunderbird).

**Comment by kohlhase** [comment]
irrelevant now.
