### ISSUE TITLE
sort out data/dist in s-data1.mcd and s-dist1.mcd

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#16]
_migrated from Trac, where originally posted by **kohlhase** on 5-Jan-2008 11:12am_

Until now, the examples in s-data1.mcd and s-dist1.mcd are just copies from the old statistics.mcd in the MathML quarry. They need to be sorted out semantically.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 6-Jan-2008 11:04pm_

Again, we need a policy decision: are we going to separate the two?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 7-Jan-2008 5:15am_

Replying to [comment:4 jhd]:

> Again, we need a policy decision: are we going to separate the two?

I personally think that the OM way of doing things makes more sense, but I would like to hear David's and Olga's opinion on this. In contrast to the multiset case, where we do not seem to have any choice for syntactic reasons. You are right, we do have a choice here. 

Of course, if we take them apart as suggested by the OM CDs, then we may have problems with the pragmatic to strict conversion in MathML3. James, I am unfamiliar with these statistics things. Are there syntactical ways the dist and data cases can be distinguished automatically, or is the distinction automatic?

If there are, then I have the feeling that we can either separate them (we can do the conversion automatically), but we do not gain much by it. If there are not, then we should really separate but we have problems with the legacy material. :-(

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 7-Jan-2008 8:20am_

Replying to [comment:5 kohlhase]:

> Replying to [comment:4 jhd]:
> 
> > Again, we need a policy decision: are we going to separate the two?
> > I personally think that the OM way of doing things makes more sense, but I would like to hear David's and Olga's opinion on this. In contrast to the multiset case, where we do not seem to have any choice for syntactic reasons. You are right, we do have a choice here. 
> 
> Of course, if we take them apart as suggested by the OM CDs, then we may have problems with the pragmatic to strict conversion in MathML3. James, I am unfamiliar with these statistics things. Are there syntactical ways the dist and data cases can be distinguished automatically, or is the distinction automatic?
> I think we can "if it's unary it's on a distribution, else it's on data" (no-one does statistics sensibly on one datum) will work for most things (you have to add the extra arument for 'moment' etc.).
> If there are, then I have the feeling that we can either separate them (we can do the conversion automatically), but we do not gain much by it. If there are not, then we should really separate but we have problems with the legacy material. :-(
> I think we do gain by separation. Statistics packages (Splus, SPSS etc.) will understand s-data but not s-dist, whereas algebraic packages will largely do the converse. Not separating puts more burden on phrasebooks.

**Comment by kohlhase** [comment]
this is MathML and thus obsolete.
