### ISSUE TITLE
Sort out integrals between OpenMath and MathML

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#17]
_migrated from Trac, where originally posted by **kohlhase** on 5-Jan-2008 11:15am_

Integrals are used differently in OpenMath and MathML. In OpenMath, we have two symbols <code>int**calculus1**</code> for the indefinite integral and defint**calculus1** for the definite integral. Both are operators applied to functions (to be constructed by <lambda/>). In MathML we have the <el>int</el> element for definite and indefinite integrals, and it can both be used both as a binder and as an applied operator.

Both usage patterns are sensible, but we must (the CDs mandate it) distinguish between binder- and applied symbols. The question now is how to best deal with pragmatic representations of integrals, there are lots of them out there.

The tentative agreement in the MathML WG is that we should leave only the MathML-style integrals in the MathML CD(s) and leave the other's to the OpenMath CDs.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 23-Jan-2008 8:23am_

"The tentative agreement in the MathML WG is that we should leave only the MathML-style integrals in the MathML CD(s) and leave the other's to the OpenMath CDs." but "In MathML we have the <el>int</el> element for definite and indefinite integrals, and it can both be used both as a binder and as an applied operator." I don't see how this can be mad to work, in two (related) ways:
(a) How can a symbol be both a binder and an operator - I thought one of the advantages of OM was that it distinguished;
(b) isn't definit fundamentally different from int?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:39pm_

rescheduling.

**Comment by kohlhase** [comment]
obsolete now
