### ISSUE TITLE
joint format for properties

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#19]
_migrated from Trac, where originally posted by **kohlhase** on 6-Jan-2008 8:57am_

OM2 CDs use <CMP> and <FMP> for properties, while MathML CDs use 

```
<property>
  <description><p>foo</p></description>
  <![CDATA[<apply>...</apply>]]>
</property>
```

We have to unify these, I suggest to have some thing like 

```
<property>
  <CMP><p>foo</p></CMP>
  <FMP><math><apply>...</apply></FMP>
</property>
```

Where FMP also allows <OMOBJ> instead of <math>

This would also get rid of the problem that in OM2CDs we do not know whether CMPs and FMPs denote the same property in different formats or different one (without the other format).

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:07pm_

rescheduling

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:23pm_

rescheduling

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 19-May-2014 2:33pm_

This looks similar to #140. Can one be closed in favour of the other?

**Comment by kohlhase** [comment]
there are no MathML CDs any more
