### ISSUE TITLE
Write a new OM/MathML alignment document

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#2]
_migrated from Trac, where originally posted by **kohlhase** on 26-Oct-2007 5:20am_

This document should specify the alignment of OM3/MathML3, and specify transformation style sheets. It may be published as a joint document with the W3C.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 26-Oct-2007 7:29am_

DPC circulated the previous document, which looks like a good starting point.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 30-Oct-2007 5:11am_

James could you attach the document to this issue, or supply the link, I remember that you posted it, but I cannot find it at the moment.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 30-Oct-2007 8:00am_

The original alignment document, as per website (Thanks, David)

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OpenMath.github.io/issues/49
