### ISSUE TITLE
joint format for examples

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#20]
_migrated from Trac, where originally posted by **kohlhase** on 6-Jan-2008 9:00am_

The same problem as issue [19](https://trac.kwarc.info/OM3/ticket/19) only for examples

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:23pm_

rescheduling

**Comment by kohlhase** [comment]
there are no more MathML CDs
