### ISSUE TITLE
symbols for basic sts types?

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#27]
_migrated from Trac, where originally posted by **kohlhase** on 27-Jan-2008 5:17am_

the baisc types used in the *.sts and *.mts files often variables, should we make them constants, then we need a CD for those that are not in omtypes.ocd, mathmltypes.ocd, sts.ocd

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 27-Jan-2008 8:27am_

Not quite sure what is meant here.
If one means
<Signature name="times">
<OMOBJ>
 <OMA>
  <OMS name="mapsto" cd="sts"/>
  <OMA>
   <OMS name="nassoc" cd="sts"/>
   <OMV name="AbelianSemiGroup"/>
  </OMA>
  <OMV name="AbelianSemiGroup"/>
 </OMA>
</OMOBJ>
</Signature>

then AbelianSemiGroup is a variable not a constant deliberately: STS (Davenport2000) does NOT impose a fixed classification of types, and the semantics of AbelianSemiGroup are NOT specified. In particular, there are differences between constructive and non-constructive semantics here (Davenport et al1991a). Moving to a fixed classification would be a major change.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 28-Jan-2008 6:57am_

Replying to [comment:1 jhd]:

>  STS (Davenport2000) does NOT impose a fixed classification of types, and the semantics of AbelianSemiGroup are NOT specified. In particular, there are differences between constructive and non-constructive semantics here (Davenport et al1991a). Moving to a fixed classification would be a major change.

James, could you please attach these two papers to this bug? Or point to where they are avaiable on the web?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 29-Jan-2008 12:17am_

Davenport2000 is the standard STS paper:  http://portal.acm.org/citation.cfm?id=362014 http://staff.bath.ac.uk/masjhd/OpenMath/sts2.pdf (if there is a copy on OpenMath.org, Google doesn't find it).
Davenportetal1991a is http://portal.acm.org/citation.cfm?id=120694.120699

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:39pm_

rescheduling.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/39
