### ISSUE TITLE
New Roles for Types?

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#28]
_migrated from Trac, where originally posted by **kohlhase** on 27-Jan-2008 5:19am_

if we have many types (and MathML3/OM3) acknowledge the existence of type systems, should we introduce new roles for types in CDs?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 27-Jan-2008 8:42am_

We could do. OM currently acknowledges the existene of type systems, but does not privilege any one such, though in practice STS is there as "not to be contradicted", at least as far as arities are concerned.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:23pm_

rescheduling

**Comment by kohlhase** [comment]
this is now rolled into https://github.com/OpenMath/OMSTD/issues/39
