### ISSUE TITLE
FMP type=alias

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#32]
_migrated from Trac, where originally posted by **kohlhase** on 28-Jan-2008 7:02am_

James Davenport suggested that option 3 might be made more palatable by 
introducing a new kind of FMP to content dictionaries, so that we could 
write

```

<FMP type="alias">
  <OMOBJ>
    <OMA>
      <OMS cd="relation1" name="eq"/>
      <OMS cd="arith1" name="sum"/>
      <OMS cd="XXX" name="YYY"/>  
    </OMA>
  </OMOBJ>
</FMP>
```

This would presumably reside in the old arith1.ocd and allow people to 
transparently (and maybe automatically) move over to the new joint CDs.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **polx** on 28-Jan-2008 10:32am_

What benefit can there be to type alias ?
If the goal is to allow any system to transparently replace then the FMP without the attribute has, I believe, the same semantic, or?
pau;

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 28-Jan-2008 9:34pm_

That wasn't the only motivation for making this proposal, by any means.
It implies that a DefMP (FMP type="defining") which was merely an equality could be explicitly flagged as such, so a system coulld reasonably "only understand" these FMPs, whereas a more general DefMP would require more analysis.
I hope that this partially answers polx's point: more genrally the idea of 'defining' is to say that this is more than just equality - see the LandauIn discussion.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:25pm_

rescheduling

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/38
