### ISSUE TITLE
Allow for metadata in smaller units than whole CDs

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#40]
_migrated from Trac, where originally posted by **clange** on 13-Jun-2008 5:26pm_

… as single symbols or examples can also have distinct authors. See http://kwarc.info/projects/swim/pubs/semwiki08-notation-semantics.pdf, section 3 and 4 for a motivation from a use case.

This proposal is related to #38 and #39, as the latter approaches would easily allow for metadata anywhere.

As a reasonable granularity for metadata, I propose
- the CD level (as we have it now in OM2)
- the symbol level (CDDefinitions or signatures or notation definitions)
- some children of CDDefinition: CMP, FMP, Example, and related ones to be introduced in OM3. It's easy to imagine that an Example has a different author than the CDDefinition itself or than a CMP within the CDDefinition.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 13-Jun-2008 11:10pm_

This certainly seems reasonable, and the use case "It's easy to imagine that an Example has a different author than the CDDefinition itself or than a CMP within the CDDefinition" is pretty compelling.
If it falls out of the others, so much the better.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:49am_

Still reasonable IMHO but would require a major redesign.  I think we are not ready for this, so feel free to close.

**Comment by kohlhase** [comment]
no longer relevant.
