### ISSUE TITLE
Denotation official of CDs

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#7]
_migrated from Trac, where originally posted by **kohlhase** on 6-Nov-2007 3:53pm_

OpenMath2 standard only allows 'official' status for CDs approved by the OM Society. This seems overly proprietary. The MathML CDs should also be official. Change in OpenMath 3?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 6-Jan-2008 6:06pm_

I don't believe this is a serious issue in the long term. The OpenMath Society is a permanent body, as is W3C, but NOT the MathML WG. Hence, unless W3C itself wishes to take over ownership, which I believe (but do not know) it is unlikely to do, ownership must rest with OM Society. 
There is a short-term issue, which is important in several ways. OM Society should agree (?in Barcelona) that it will accept the MathML3 CDs in block (if at all), to prevent any divergence etc.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **david** on 29-Jan-2008 1:31am_

Personally I think we should drop this in OM3.

I think it's an artificial barrier to getting contributed CDs. It's telling that since the end of the _first_ EU funded OpenMath project, there have not, as far as I'm aware, been any new official CDs. Unless the OM society has people working full time on this again, I suspect that we will never ave the resources to independantly verify CDs. The result is that all CDs are permanently held in experimental status.
which avoids the problem but means that the end user has no real view of the stability.

I'd rather see the stability being self-assessed. If I think my CD is experimental and I may change it tomorrow, let me flag it as such. If I have stopped working on it and want to freeze the CD let me classify it as stable.

We could still assign the core CDs to OM society (and/or W3C) to give them a special status without taking over the status field in the CD in a way that I think is unhelpfully negative towards contributed CDs (een CDs contributed by core members, such as the RIACA CDs which have been "experimental" forever...

David

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 29-Jan-2008 4:41am_

I think we are moving towards a consensus here. We should probably knock this off in the next meeting.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 30-Jan-2009 9:04am_

Replying to [comment:7 kohlhase]:

> I think we are moving towards a consensus here. We should probably knock this off in the next meeting. 
> Which looks like being at CICM 09 in Canada. The original rules were there for a purpose at the time. Maybe we should look at Internet RFCs for a mechanism here?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:38pm_

rescheduling.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/47
