### ISSUE TITLE
attribute CD/@version

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#70]
_migrated from Trac, where originally posted by **clange** on 6-Sep-2008 10:42pm_

It would be nice to have an attribute `CD/**version**`.  That would make processing easier, particularly in applications that support both OpenMath 2 and 3.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:50am_

Might still be relevant depending on how we'd like to handle the OpenMath 2→3 transition

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/46
