### ISSUE TITLE
Title as a child of CD as well

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#72]
_migrated from Trac, where originally posted by **clange** on 8-Sep-2008 4:26pm_

If the purpose of a `Title` of a `CDDefinition` is giving a symbol a human-readable title, I think we should have the same for CDs as well.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:53am_

`Title` might have been one of those experimental elements that were added during the work on MathML 3 around 2008.  I no longer remember whether we wanted to keep it.  If so, this concern is still valid.

**Comment by kohlhase** [comment]
oboslete now.
