### ISSUE TITLE
Support discussion element

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#74]
_migrated from Trac, where originally posted by **clange** on 8-Sep-2008 6:45pm_

If this is kept in OpenMath 2+/3, add support for it to 
- the ontology 
- the Krextor extraction module

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:34am_

This ticket refers to an XML element `discussion` which had once existed in some CDs developed around 2008, while MathML 3 was developing. I could very well imagine that this is now obsolete.

**Comment by kohlhase** [comment]
obsolete
