### ISSUE TITLE
general formulation issues

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#75]
_migrated from Trac, where originally posted by **jauecker** on 8-Sep-2008 8:27pm_

_Chris:_

---

The references to the CDs promise a 'full semantic definition'.

This is misleading in two ways:
1.  It implies that such a thing exists and would be useful if it did!
2.  More pertinently, what is in a typical CD is anything but 'full'.

Better wordings:

further semantic information

further discussion of the mathematical semantics

...

---

The phrase:

 takes no parameters

is sometimes used but, I think, when something does 'take parameters'
then they are referred to as 'arguments' (the latter is I think, our
favoured term).  Also, maybe some zero-argument cases are not
made explicit in this way.

---

This type of language appears very often:

`An operator representing the foobar of its argument.'

when I think we mean either (or maybe both of):

`An operator representing foobar'
`An operator representing the value of foobar applied to its argument.'

---

The usage 'This CD holds ...' sounds a little strange.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:26pm_

rescheduling

**Comment by kohlhase** [comment]
moved tto https://github.com/OpenMath/OMSTD/issues/36
