### ISSUE TITLE
Completeness of the CDs

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#77]
_migrated from Trac, where originally posted by **jauecker** on 8-Sep-2008 8:31pm_

_Chris:_

Also, I have not yet thought systematically about the 'completeness'
problem (and only a little about 'consistency':-).  My feeling is that
there is a lot of K-12 notation that is missing, presumably because it
has not been needed commercially and is not needed when using
'classical mathematical software applications'. This latter
restriction must be removed as a lot of modern systems are rapidly
coming into use now, eg GeoGebra and friends.  As Neil will attest,
such new stuff is also making its presence felt commercially.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jauecker** on 12-Sep-2008 1:11pm_

_Michael:_

I would really be interested in examples or a full list of these

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 12-Sep-2008 1:32pm_

Replying to [ticket:77 jauecker]:

> Also, I have not yet thought systematically about the 'completeness'
> problem (and only a little about 'consistency':-).  My feeling is that
> there is a lot of K-12 notation that is missing, presumably because it
> has not been needed commercially and is not needed when using
> 'classical mathematical software applications'. This latter
> restriction must be removed as a lot of modern systems are rapidly
> coming into use now, eg GeoGebra and friends.  As Neil will attest,
> such new stuff is also making its presence felt commercially.
> I think this overstates the case, but I admit completely to the geometry problem. The other area I can think of is units, and I need to make these part of 'official'.

**Comment by kohlhase** [comment]
there is no way to reach completeness.
