### ISSUE TITLE
Reconsider CDUses

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#79]
_migrated from Trac, where originally posted by **clange** on 9-Sep-2008 4:11pm_

Do we want to keep `CDUses`?  I think if we do we need to revise it anyway.  Here's what the 2.0 spec says about it:

```
The content of this element should be a series of CDName elements, each naming a Content
Dictionary used in the Example and FMPs of the current Content Dictionary. This element is
optional and deprecated since the information can easily be extracted automatically.
```

What if the Examples and FMPs of the current CD refer to CDs in other CDBases?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 23-Aug-2010 10:38pm_

IIUC it's deprecated anyway.  But can we afford something that does not even _work_, even if we deprecate it?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:54am_

Still a valid concern IMHO.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/27
