### ISSUE TITLE
Update to new URI spec

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#9]
_migrated from Trac, where originally posted by **polx** on 6-Nov-2007 11:05pm_

Reference to RFC 2396 is obsolete, we should point to RFC 3986 and remove the note about fancy encoding (since the newer one suggests UTF-8).

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **polx** on 6-Nov-2007 11:09pm_

on a related note, I wonder if full URI arithmetic such as ../neighbour-collection/othercd3 is not wished.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 8-Nov-2007 12:29pm_

Paul, 

I think that you should just do this, and add the corresponding change marks. This seems uncontroversial to me. I am assigning this to you.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:36pm_

rescheduling

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/OMSTD/issues/29
