### ISSUE TITLE
functions as parameters

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#90]
_migrated from Trac, where originally posted by **jauecker** on 21-Sep-2008 12:06pm_

_Peter:_

arith1.sum, calcucus1.diff etc. all take a function as a parameter.
   There are several quirks with this:
- First, there ARE no functions in OM. From the examples I found  
  that this
   is referring to fns1.lambda-expressions.
- Handling around these is -- from a computer-algebra point of
   view -- rather cumbersome.
- In CA, you very frequently use expressions for this purpose and  
  specify
   the variable as an additional parameter as in diff(x^2+1, x),  
  we'd highly
   prefer this.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 25-Feb-2011 12:30pm_

this relates to the expressions vs. functions debate, rescheduling.

**Comment by kohlhase** [comment]
there is no problem with higher-order functions whatsoever, only STS cannot cover it.
