### ISSUE TITLE
Enable validation form again

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#96]
_migrated from Trac, where originally posted by **clange** on 4-Nov-2008 12:20am_

Paul, could you please re-enable the validation form at http://www.openmath.org/software/validate.html?  Not that I'd need it for myself, but I once spent 1½ hours on implementing a Perl CGI script that runs the XSLT validator. Do you still have it, or should I rather resend the mail?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **polx** on 4-Nov-2008 11:23am_

Request to our sysadmins active... maybe a week from now.

paul

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 16-May-2014 12:55am_

The online validation form has been offline for a long time, so I think it won't come back any time soon.  Or will it, once we move the web server?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **polx** on 20-May-2014 6:19pm_

Christoph,
the server has been moved since almost a year now.
It would be easy to get java running there, if I do not mistake.
But maybe your Perl contribution would help.

Again something for Jan Willem.

paul

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 2-Jun-2014 12:10pm_

Replying to [comment:3 polx]:

> the server has been moved since almost a year now.
> It would be easy to get java running there, if I do not mistake.

I don't exactly recall how that XSLT was implemented, but if it is XSLT 2.0 then it needs Saxon and thus Java.

> But maybe your Perl contribution would help.

I don't recall either where this Perl code is that I once wrote.  I might have emailed it to you, Paul, so I could dig into my archived emails.  Or I might have uploaded it to the server (no time to look there right now).  IIRC the Perl script was a CGI script that would take CDs uploaded via a web form and feed them into that XSLT to have them validated.

> Again something for Jan Willem.

OK, same procedure as with the other ticket.  **Jan** Willem, please log into the Trac and assign the ticket to yourself.

**Comment by kohlhase** [comment]
that has been done on the new web site.
