### ISSUE TITLE
Duplicate CDDefinition finfield1#field_by_conway

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#97]
_migrated from Trac, where originally posted by **clange** on 4-Nov-2008 1:24pm_

According to Murphy's law, something went wrong when I started to import the OpenMath 2 CDs into the wiki, and this time the wiki is not the culprit.  The finfield1 CD contains two different definitions of the symbol field_by_conway.  Now I suppose this is a case where we do need to edit the old CDs ;-)  (But for this particular task I'd rather recommend a text/XML editor than the wiki.)

**Michael**, there is no suitable component for reporting this.  Should we create one?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 4-Nov-2008 3:05pm_

yes, we should create a component for this, and we should explicitly cc James on this bug

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 4-Nov-2008 3:57pm_

yes - I've seen it, but when I tried to look for the OCD, I got a blank file. If some-one could e-mail me the OCD (it's new since I last took a dump, I think) I'll look at it.
James

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 4-Nov-2008 4:14pm_

E-mail?? You mean you don't see anything in this file? https://svn.openmath.org/www/cdfiles2/cd/finfield1.ocd

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 4-Nov-2008 6:52pm_

Replying to [comment:1 kohlhase]:

> yes, we should create a component for this, and we should explicitly cc James on this bug
> Created components
> - OM2 Standard CDs
> - OM2 Contrib CDs
>   with James being the owner.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 4-Nov-2008 10:48pm_

Replying to [comment:3 clange]:

> E-mail?? You mean you don't see anything in this file? https://svn.openmath.org/www/cdfiles2/cd/finfield1.ocd
> I didn't when I last looked, but I do now. Browser time-out?

There are other problems with this CD (which I haven't seen before - my fault): priitive_element comes in unary and binary versions, which OM does not allow (you didn't pick this up automatically, as it's only in the comments. minimal_polynomial has the same problem.
My current view is tha the first field_by_conway is plain broken, and should be deleted, but I'd like to run this past a local expert, and also by Arjeh if possible. Does any-one know if he is reading e-mail?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **lars_h** on 26-Oct-2013 7:46pm_

Ran across this (in what is shown at www.openmath.org) and went to report it, but it already had a ticket. Yay, less work for me! :-)

Replying to [comment:5 jhd]:

> My current view is tha the first field_by_conway is plain broken, and should be deleted,

I concur with that. The first description's GF(q)[X]/(C(X)) plainly isn't a field for n>1, since the polynomial C(X) by definition splits in GF(q). It needs to be done over GF(p), as it is by definition in GF(p)[X] that C(X) is irreducible.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 27-Oct-2013 6:22am_

Thanks for reminding me of this one. Unfortunately I can't access the SVN to chase it down.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/CDs/issues/27
