### ISSUE TITLE
logic1p is not a CD, just a CDDefinition

### ISSUE THREAD

**Issue by jbs1** [OpenMath/OM3#99]
_migrated from Trac, where originally posted by **clange** on 4-Nov-2008 6:58pm_

logic1p consists just of one CDDefinition element

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 4-Nov-2008 11:03pm_

Replying to [ticket:99 clange]:

> logic1p consists just of one CDDefinition element
> Wher do you get logic1p from?

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 4-Nov-2008 11:07pm_

Replying to [comment:1 jhd]:

> Replying to [ticket:99 clange]:
> 
> > logic1p consists just of one CDDefinition element
> > Wher do you get logic1p from?
> > https://svn.openmath.org/www/cdfiles2/contrib/cd/logic1p.ocd

(Note that I created the Trac component "OM2 Contrib CDs" for the contributed CDs in that directory.)

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 4-Nov-2008 11:11pm_

Replying to [comment:2 clange]:

> Replying to [comment:1 jhd]:
> 
> > Replying to [ticket:99 clange]:
> > 
> > > logic1p consists just of one CDDefinition element
> > > Wher do you get logic1p from?
> > > https://svn.openmath.org/www/cdfiles2/contrib/cd/logic1p.ocd
> 
> (Note that I created the Trac component "OM2 Contrib CDs" for the contributed CDs in that directory.)
> Thanks. I forgot the extra 'contrib'. God knows where this CD came from, but I would like to shoot it (and talk to the author) It makes MathML2 condition look positively reasonable! Furthermore, maing things convenient for textbook authors ought not, in my view, to be an OM motivation.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **clange** on 4-Nov-2008 11:30pm_

Replying to [comment:3 jhd]:

> Thanks. I forgot the extra 'contrib'. God knows where this CD came from, but I would like to shoot it (and talk to the author) It makes MathML2 condition look positively reasonable! Furthermore, maing things convenient for textbook authors ought not, in my view, to be an OM motivation.
> Just grep for "taka" and ".tfb".  Looks like those other CDs from Kōbe University (http://www.math.kobe-u.ac.jp/OCD).

I agree that this symbol is not well designed.  In particular, the FMP is wrong, as the variable _n_ is once referenced outside of the binder.  However, I think that there are many motivations for using OpenMath.  Think of adaptive documents, as e.g. in ActiveMath.  There you may want to have "semantic" markup for symbols whose appearance you want to adapt, even though your semantic markup is not sufficient from a computational or logical point of view.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **jhd** on 5-Nov-2008 11:07pm_

Replying to [comment:4 clange]:

> I agree that this symbol is not well designed.  In particular, the FMP is wrong, as the variable _n_ is once referenced outside of the binder.  
> Quite so.
> However, I think that there are many motivations for using OpenMath.  Think of adaptive documents, as e.g. in ActiveMath.  There you may want to have "semantic" markup for symbols whose appearance you want to adapt, even though your semantic markup is not sufficient from a computational or logical point of view.
> But if we are to process such a definition, it MUST have a meaning, even if incomplete (formally, a \lambda-expression with bound variables, that is waiting to be applied). If we just want it to "look like" something, then presentation MathML is there.

**Comment by kohlhase** [comment]
moved to https://github.com/OpenMath/CDs/issues/26
